add editor config and mardown checks

diff --git a/.github/workflows/terrafrom-pipeline.yml b/.github/workflows/terrafrom-pipeline.yml
--- a/.github/workflows/terrafrom-pipeline.yml
+++ b/.github/workflows/terrafrom-pipeline.yml
@@ -1,4 +1,4 @@
-name: terraform_pipeline
+name: terraform_pipeline_non_prod
 on:
   push:
     branches:    
@@ -10,10 +10,41 @@ on:
     branches: [ "main" ]
 env:
   tf_actions_working_dir: ${{ vars.tf_actions_working_dir }}
+  environment: test
 defaults:
   run:
     shell: bash
 jobs:
+  initial-start:
+    runs-on: ubuntu-latest
+    name: initial start
+    steps:
+      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
+
+  run-editorconfig-check: 
+    needs: [initial-start]
+    runs-on: ubuntu-latest
+    name: .editorconfig check
+    steps:
+      - uses: actions/checkout@v3
+      - uses: editorconfig-checker/action-editorconfig-checker@main
+      - run: editorconfig-checker
+  
+  run-markdown-lint: 
+    needs: [initial-start]
+    runs-on: ubuntu-latest
+    name: markdownlint lint
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        
+      - name: Install dependencies
+        run: npm install -g markdownlint-cli
+
+      - name: Run Markdown linting
+        run: |
+          markdownlint **/*.md
+  
   terraform-fmt:
     name: 'terraform-fmt'
     runs-on: ubuntu-latest
@@ -31,32 +62,43 @@ jobs:
       run: terraform fmt -check -recursive
       continue-on-error: false
 
-  checkov-job:
+  run-checkov:
     runs-on: ubuntu-latest
-    needs: [terraform-fmt]
-    name: checkov-job
+    env:
+      CHECKOV_SKIPPED_CHECKS:
+    name: analysis with Checkov 
     steps:
       - name: Checkout repo
         uses: actions/checkout@master
 
-      - name: Run Checkov action
+      - name: Checkov GitHub Action
         id: checkov
         uses: bridgecrewio/checkov-action@master
         with:
           directory: .
           #skip_check: CKV_AWS_2 # optional: skip a specific check_id. can be comma separated list
           framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
-          output_format: sarif # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
+          output_format: cli # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
+          output_file_path: console
+          skip_check: ${{ env.CHECKOV_SKIPPED_CHECKS }}
+          quiet: true
+      # - name: Upload SARIF file
+      #   uses: github/codeql-action/upload-sarif@v2
+
+      #   # Results are generated only on a success or failure
+      #   # this is required since GitHub by default won't run the next step
+      #   # when the previous one has failed. Security checks that do not pass will 'fail'.
+      #   # An alternative is to add `continue-on-error: true` to the previous step
+      #   # Or 'soft_fail: true' to checkov.
+      #   if: success() || failure()
+      #   with:
+      #     sarif_file: results.sarif
 
   terraform-validate:
     name: 'terraform-validate'
-    strategy:
-      max-parallel: 1
-      matrix:
-        environment: ['test', 'staging', 'production']
     needs: [terraform-fmt, checkov-job]
     runs-on: ubuntu-latest
-    environment: ${{ matrix.environment }}
+    environment: ${{ env.environment }}
     defaults:
       run:
         working-directory: ${{ env.tf_actions_working_dir }}
@@ -78,13 +120,9 @@ jobs:
 
   terraform-plan:
     name: 'terraform-plan'
-    strategy:
-      max-parallel: 1
-      matrix:
-        environment: ['test', 'staging', 'production']
     needs: [terraform-fmt, checkov-job, terraform-validate]
     runs-on: ubuntu-latest
-    environment: ${{ matrix.environment }}
+    environment: ${{ env.environment }}
     defaults:
       run:
         working-directory: ${{ env.tf_actions_working_dir }}
